### ISSUE TITLE
Expression Exchange master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/expression-exchange#3]
## Design
- [x] **Sim folder and design doc created** (Date: 08/14/2015) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 08/21/2015)
- [x] **Design concept complete**  (Date: 09/10/2015)
- [x] **Wireframes complete** (Date: 11/05/2015) 
- [x] **Mockups complete** (Date: 11/16/2016) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 03/30/2017) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 06/20/17) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [ ] Sim primer draft
  - [x] Verify credits
- [ ] **Post-publication items** 
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [x] Hold postmortem if applicable (n/a) 

## Implementation
- [x] **Repository created** (Date: 10/22/2015)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 01/05/2016)
- [x] **Sim is "feature complete"** (Date: 03/03/2017) 
- [x] **Code review completed** (Date: 05/30/2017) 
- [x] **Published** (Date: 07/03/2017) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [x] **Dev testing started** (Date: 11/17/2016) 
- [x] **Dev testing completed** (Date: 06/23/2017) 
- [x] **First RC published** (Date: 06/26/2017)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 06/30/2017)

*note - dev testing was started quite early on this sim to meet project goals for an early version to be used with teachers

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed**
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ files
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing completed** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matricies put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by ariel-phet** [comment]
@amanda-phet can you do the "lead designer" sign-off step. I took a look at the pointer areas briefly and some things seemed a bit funky with the "1" and "-1", in addition, it looked to me as though the touch areas for the accordion box open/close buttons could be increased.

In addition, it would be good to get rolling on the the teacher tips and a rough primer draft.

**Comment by amanda-phet** [comment]
@ariel-phet what is the timeline for publication?

**Comment by ariel-phet** [comment]
@amanda-phet I would hope we get an RC out this week, so hopefully published the week of the 12th or 19th

**Comment by amanda-phet** [comment]
Thanks @ariel-phet . I will be sure to have teacher tips done before publication.

**Comment by ariel-phet** [comment]
@amanda-phet since we are now in dev testing can you do the "lead designer" sign-off step?

**Comment by jbphet** [comment]
Checklist completed - closing.

**Comment by ariel-phet** [comment]
@jbphet your parts of the checklist are completed, yes, but I still have some things to do :)

Reopening

**Comment by ariel-phet** [comment]
@amanda-phet once an activity has been uploaded, can you make a primer issue and close the checklist?

**Comment by amanda-phet** [comment]
An activity is uploaded.
